version: '3'
services:
  monolog_addons:
    image: webdevops/php-dev:${PHP_VERSION:-latest}
    ports:
      - ${PHP_SERVER_PORT:-9001}:9001
      - ${PHP_PORT:-9999}:9000
    volumes:
      - ../:/app:delegated
    working_dir: /app
